# Generación de Texto con modelos GPT

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Ohtar10/icesi-nlp/blob/main/Sesion5/1-text-generation.ipynb)

En este notebook harémos uso de un modelo tipo GPT-2 pre-entrenado en idioma español que utilizaremos para generar texto a partir de un contexto inicial que proveerémos. Luego, harémos fine tuning a este modelo con un dataset de chistes en español y observar como cambia la generación de texto en función del dataset que utilicemos.

#### Referencias
- Dataset: https://huggingface.co/datasets/mrm8488/CHISTES_spanish_jokes
- [Improving Language Understanding by Generative Pre-Training](https://cdn.openai.com/research-covers/language-unsupervised/language_understanding_paper.pdf)
- [Natural Language Processing with Transformers: Building Language Applications With Hugging Face](https://www.amazon.com/Natural-Language-Processing-Transformers-Applications/dp/1098103246)
- [GPT2 Spanish](https://huggingface.co/DeepESP/gpt2-spanish)
- [Fine-Tune a non-Englush GPT-2 Model with Huggingface](https://www.philschmid.de/fine-tune-a-non-english-gpt-2-model-with-huggingface)

In [1]:
import pkg_resources
import warnings

warnings.filterwarnings('ignore')

installed_packages = [package.key for package in pkg_resources.working_set]
IN_COLAB = 'google-colab' in installed_packages

C:\Users\apapa\AppData\Local\Temp\ipykernel_228\2396000874.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources

In [2]:
#!test '{IN_COLAB}' = 'True' && wget  https://github.com/Ohtar10/icesi-nlp/raw/refs/heads/main/requirements.txt && pip install -r requirements.txt
!test '{IN_COLAB}' = 'True' && sudo apt-get update -y
!test '{IN_COLAB}' = 'True' && sudo apt-get install python3.10 python3.10-distutils python3.10-lib2to3 -y
!test '{IN_COLAB}' = 'True' && sudo update-alternatives --install /usr/local/bin/python python /usr/bin/python3.11 2
!test '{IN_COLAB}' = 'True' && sudo update-alternatives --install /usr/local/bin/python python /usr/bin/python3.10 1
!test '{IN_COLAB}' = 'True' && pip install lightning datasets 'transformers[torch]' sentence-transformers torchinfo evaluate

"test" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"test" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"test" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"test" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"test" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

## Generative pre-training Transformer - GPT

![](../assets/gpt.png)

Los modelos tipo GPT, introducidos por Radfor, et.al., de OpenAI, al igual que los modelos BERT, hacen uso extensivo de la arquitectura de transformers como hemos estado viendo. Las diferencias claves se podrían resumir en:

1. GPT utiliza bloques de **Transformer Decoder** encadenados, mientras que el modelo BERT utiliza bloques de *Transformer Encoder*
2. GPT se centra en la generación de texto basado en un contexto, la tarea principal es la predicción del siguiente token en la secuencia, mientras que BERT se centra en el completado de partes de una secuencia, en función de un contexto anterior y posterior a la secuencia de entrada. Entonces BERT se centra en la construicción de representación de lenguage, mientras que GPT se centra en la generación de texto en función de un contexto.

Sin embargo, ambos se basan en la misma premisa de pre-entrenar el modelo en tareas no-supervisadas o semi-supervisadas para que el modelo aprenda las representaciones semánticas del lenguage y luego al modelo se le pueda hacer fine tuning a tareas posteriores.

In [3]:
import torch
import transformers
from transformers import AutoModelForCausalLM, AutoTokenizer


device = "cuda" if torch.cuda.is_available() else "cpu"
model_name = "mrm8488/spanish-gpt2"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(model_name).to(device)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token  

model.config.pad_token_id = tokenizer.pad_token_id

model.resize_token_embeddings(len(tokenizer))

model

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: mrm8488/spanish-gpt2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
The new embeddings will be initialized from a multivariate normal distribution that has old embeddings' mean and covariance. As described in this article: https://nlp.stanford.edu/~johnhew/vocab-expansion.html. To disable this, use `mean_resizing=False`

GPT2LMHeadModel(
  (transformer): GPT2Model(
    (wte): Embedding(50266, 768)
    (wpe): Embedding(1024, 768)
    (drop): Dropout(p=0.0, inplace=False)
    (h): ModuleList(
      (0-11): 12 x GPT2Block(
        (ln_1): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (attn): GPT2Attention(
          (c_attn): Conv1D(nf=2304, nx=768)
          (c_proj): Conv1D(nf=768, nx=768)
          (attn_dropout): Dropout(p=0.0, inplace=False)
          (resid_dropout): Dropout(p=0.0, inplace=False)
        )
        (ln_2): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
        (mlp): GPT2MLP(
          (c_fc): Conv1D(nf=3072, nx=768)
          (c_proj): Conv1D(nf=768, nx=3072)
          (act): NewGELUActivation()
          (dropout): Dropout(p=0.0, inplace=False)
        )
      )
    )
    (ln_f): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
  )
  (lm_head): Linear(in_features=768, out_features=50257, bias=False)
)

In [4]:
modules = [m for m, _ in model.named_modules()]
modules

['',
 'transformer',
 'transformer.wte',
 'transformer.wpe',
 'transformer.drop',
 'transformer.h',
 'transformer.h.0',
 'transformer.h.0.ln_1',
 'transformer.h.0.attn',
 'transformer.h.0.attn.c_attn',
 'transformer.h.0.attn.c_proj',
 'transformer.h.0.attn.attn_dropout',
 'transformer.h.0.attn.resid_dropout',
 'transformer.h.0.ln_2',
 'transformer.h.0.mlp',
 'transformer.h.0.mlp.c_fc',
 'transformer.h.0.mlp.c_proj',
 'transformer.h.0.mlp.act',
 'transformer.h.0.mlp.dropout',
 'transformer.h.1',
 'transformer.h.1.ln_1',
 'transformer.h.1.attn',
 'transformer.h.1.attn.c_attn',
 'transformer.h.1.attn.c_proj',
 'transformer.h.1.attn.attn_dropout',
 'transformer.h.1.attn.resid_dropout',
 'transformer.h.1.ln_2',
 'transformer.h.1.mlp',
 'transformer.h.1.mlp.c_fc',
 'transformer.h.1.mlp.c_proj',
 'transformer.h.1.mlp.act',
 'transformer.h.1.mlp.dropout',
 'transformer.h.2',
 'transformer.h.2.ln_1',
 'transformer.h.2.attn',
 'transformer.h.2.attn.c_attn',
 'transformer.h.2.attn.c_proj',
 'transformer.h.2.attn.attn_dropout',
 'transformer.h.2.attn.resid_dropout',
 'transformer.h.2.ln_2',
 'transformer.h.2.mlp',
 'transformer.h.2.mlp.c_fc',
 'transformer.h.2.mlp.c_proj',
 'transformer.h.2.mlp.act',
 'transformer.h.2.mlp.dropout',
 'transformer.h.3',
 'transformer.h.3.ln_1',
 'transformer.h.3.attn',
 'transformer.h.3.attn.c_attn',
 'transformer.h.3.attn.c_proj',
 'transformer.h.3.attn.attn_dropout',
 'transformer.h.3.attn.resid_dropout',
 'transformer.h.3.ln_2',
 'transformer.h.3.mlp',
 'transformer.h.3.mlp.c_fc',
 'transformer.h.3.mlp.c_proj',
 'transformer.h.3.mlp.act',
 'transformer.h.3.mlp.dropout',
 'transformer.h.4',
 'transformer.h.4.ln_1',
 'transformer.h.4.attn',
 'transformer.h.4.attn.c_attn',
 'transformer.h.4.attn.c_proj',
 'transformer.h.4.attn.attn_dropout',
 'transformer.h.4.attn.resid_dropout',
 'transformer.h.4.ln_2',
 'transformer.h.4.mlp',
 'transformer.h.4.mlp.c_fc',
 'transformer.h.4.mlp.c_proj',
 'transformer.h.4.mlp.act',
 'transformer.h.4.mlp.dropout',
 'transformer.h.5',
 'transformer.h.5.ln_1',
 'transformer.h.5.attn',
 'transformer.h.5.attn.c_attn',
 'transformer.h.5.attn.c_proj',
 'transformer.h.5.attn.attn_dropout',
 'transformer.h.5.attn.resid_dropout',
 'transformer.h.5.ln_2',
 'transformer.h.5.mlp',
 'transformer.h.5.mlp.c_fc',
 'transformer.h.5.mlp.c_proj',
 'transformer.h.5.mlp.act',
 'transformer.h.5.mlp.dropout',
 'transformer.h.6',
 'transformer.h.6.ln_1',
 'transformer.h.6.attn',
 'transformer.h.6.attn.c_attn',
 'transformer.h.6.attn.c_proj',
 'transformer.h.6.attn.attn_dropout',
 'transformer.h.6.attn.resid_dropout',
 'transformer.h.6.ln_2',
 'transformer.h.6.mlp',
 'transformer.h.6.mlp.c_fc',
 'transformer.h.6.mlp.c_proj',
 'transformer.h.6.mlp.act',
 'transformer.h.6.mlp.dropout',
 'transformer.h.7',
 'transformer.h.7.ln_1',
 'transformer.h.7.attn',
 'transformer.h.7.attn.c_attn',
 'transformer.h.7.attn.c_proj',
 'transformer.h.7.attn.attn_dropout',
 'transformer.h.7.attn.resid_dropout',
 'transformer.h.7.ln_2',
 'transformer.h.7.mlp',
 'transformer.h.7.mlp.c_fc',
 'transformer.h.7.mlp.c_proj',
 'transformer.h.7.mlp.act',
 'transformer.h.7.mlp.dropout',
 'transformer.h.8',
 'transformer.h.8.ln_1',
 'transformer.h.8.attn',
 'transformer.h.8.attn.c_attn',
 'transformer.h.8.attn.c_proj',
 'transformer.h.8.attn.attn_dropout',
 'transformer.h.8.attn.resid_dropout',
 'transformer.h.8.ln_2',
 'transformer.h.8.mlp',
 'transformer.h.8.mlp.c_fc',
 'transformer.h.8.mlp.c_proj',
 'transformer.h.8.mlp.act',
 'transformer.h.8.mlp.dropout',
 'transformer.h.9',
 'transformer.h.9.ln_1',
 'transformer.h.9.attn',
 'transformer.h.9.attn.c_attn',
 'transformer.h.9.attn.c_proj',
 'transformer.h.9.attn.attn_dropout',
 'transformer.h.9.attn.resid_dropout',
 'transformer.h.9.ln_2',
 'transformer.h.9.mlp',
 'transformer.h.9.mlp.c_fc',
 'transformer.h.9.mlp.c_proj',
 'transformer.h.9.mlp.act',
 'transformer.h.9.mlp.dropout',
 'transformer.h.10',
 'transformer.h.10.ln_1',
 'transformer.h.10.attn',
 'transformer.h.10.attn.c_attn',
 'transformer.h.10.attn.c_proj',
 'transformer.h.10.attn.attn_dropout',
 'transformer.h.10.attn.resid_dropout',
 'transformer.h.10.ln_2',
 'transformer.h.10.mlp',
 'transformer.h.10.mlp.c_fc',
 'transformer.h.10.mlp.c_proj',
 'transformer.h.10.mlp.act',
 'transformer.h.10.mlp.dropout',
 'transformer.h.11',
 'transformer.h.11.ln_1',
 'transformer.h.11.attn',
 'transformer.h.11.attn.c_attn',
 'transformer.h.11.attn.c_proj',
 'transformer.h.11.attn.attn_dropout',
 'transformer.h.11.attn.resid_dropout',
 'transformer.h.11.ln_2',
 'transformer.h.11.mlp',
 'transformer.h.11.mlp.c_fc',
 'transformer.h.11.mlp.c_proj',
 'transformer.h.11.mlp.act',
 'transformer.h.11.mlp.dropout',
 'transformer.ln_f',
 'lm_head']

Observermos un ejemplo de generación simple.

In [5]:
text = "Había una vez"
best = 10

with torch.no_grad():
    tokens = tokenizer(text, return_tensors='pt')['input_ids'].to(device)
    print("Dimensiones de la entrada:", tokens.shape)
    output = model(input_ids=tokens)
    print("Dimensiones de la salida:", output.logits.shape)
    output = output.logits[0, -1, :]
    print("Dimensiones del último token de la secuencia:", output.shape)
    probs = torch.softmax(output, dim=-1)
    print("Dimensiones de la probabilidad de los tokens:", probs.shape)
    sorted_probs = torch.argsort(probs, dim=-1, descending=True)
    print({tokenizer.decode(token): f"{prob.cpu().numpy() * 100:.2f}%" for token, prob in zip(sorted_probs[:best], probs[sorted_probs[:best]])})

Dimensiones de la entrada: torch.Size([1, 3])
Dimensiones de la salida: torch.Size([1, 3, 50266])
Dimensiones del último token de la secuencia: torch.Size([50266])
Dimensiones de la probabilidad de los tokens: torch.Size([50266])
{' un': '30.17%', ' una': '25.06%', ',': '14.50%', ' en': '8.18%', ' que': '5.96%', '...': '5.87%', ' dos': '1.74%', '.': '0.72%', ' tres': '0.67%', ' uno': '0.34%'}

## Implementando una función de generación

Ahora, la idea es que este modelo nos sirva para generar texto de forma recurrente e incremental. En la última capa de los modelos tipo GPT encontrarémos un tensor con forma $(b, s, v)$, donde:

- $b$: Es el tamaño del bache, o la cantidad de secuencias a procesar.
- $s$: Es la longitud de la secuencia de entrada.
- $v$: Es el tamaño del vocabulario del modelo, cuantos tokens soporta.

Pero este es el tensor de salida, por qué tiene la forma de la secuencia de entrada?, porque cada posición en la salida corresponde a la la predicción del siguiente token de esa posición en la secuencia de entrada. En otras palabras, lo que obtenemos como predicción, es una secuencia de igual tamaño a la de entrada, movida un token hacia adelante, lo que efectivamente nos predice un solo token a la vez y por ende, el token que nos insteresa, es el último.

Lo que obtenemos en este tensor es además los logits de TODO el vocabulario del modelo, con los cuales podemos calcular las probabilidades de que cada uno sea el que continue en la secuencia. Hay varias formas de decodificar el siguiente token, la más fácil de implementar sería una decodificación codiciosa (greedy) del siguiente token, que consiste simplemente en seleccionar el token con la probabilidad más alta. Este es un enfoque simple y efectivo para algunos casos, pero al mismo tiempo sufre de poca variabilidad e incluso puede caer en generación repetitiva.

Otra opción es el muestreo, ya que justamente podemos obtener probabilidades del siguiente token, lo más lógico sería muestrear con esas opciones de probabilidad, de este modo podemos obtener mayor diversidad a la hora de generar el texto, al costo eso si de que haya mayor aleatoridad ya que se le daría la oportunidad a incluso tokens con baja probabilidad, de ser seleccionados.

Otra opción podría ser un balanceo entre una decodificación greedy y una por muestreo, en función de otro hiperparámetro que podemos definir. Esta sería una técnica muy común en el contexto de Reinforcement Learning llamade e-greedy. Se hace la aclaración de que en este ejemplo no harémos nada de RL, solamente se hace mención de esta técnica para balancear entre explotación y exploración.

In [6]:
import torch.nn as nn
import numpy as np
import pandas as pd
from typing import Optional, Tuple
from transformers.tokenization_utils_base import PreTrainedTokenizerBase


def generate(
        model: nn.Module, 
        tokenizer: PreTrainedTokenizerBase, 
        start: str, 
        max_length: int = 100, 
        eps: float = 0.5, 
        top_n: int = 5,
        return_iterations: bool = False,
        device: str = "cpu") -> Tuple[str, Optional[pd.DataFrame]]:

    output = [start]
    iterations = []
    with torch.no_grad():
        input_ids = tokenizer(output[-1], return_tensors='pt')['input_ids'].to(device)
        for _ in range(max_length):
            # Tomamos los logits producidos por la última capa del modelo
            # Estos corresponden al siguiente token por cada posición de la cadena
            logits = model(input_ids=input_ids).logits
            # Por lo tanto, el que nos interesa es el último, que correspondería a la
            # predicción del siguiente token después del final de la cadena original
            # A este aplicamos un softmax para obtener las probabilidades por cada
            # token del vocabulario para estar presente en la cadena.
            probs = torch.softmax(logits[0, -1, :], dim=-1)
            # Simplemente ordenamos por probabilidad de forma descendente
            sorted_tokens = torch.argsort(probs, dim=-1, descending=True)

            # Utilizamos una politica tipo e-greedy para obtener el siguiente token de la secuencia
            # Un eps>=1 quiere decir que siempre se va seleccionar el token de forma 'greedy', es decir
            # siempre se toma el token con probabilidad más alta.

            # Un eps=0 quiere decir que siempre se va a muestrear el siguiente token en función
            # de las probabilidades de cada token

            # Un 0<eps<1 va a balancear de forma binomial entre tomar el token con la
            # probabilidad más alta y muestrear el token en función de sus probabilidades. 
            if np.random.random_sample(1)[0] < eps:
                # Se toma el mejor token
                next_token = sorted_tokens[0].unsqueeze(dim=0)
            else:
                # Se muetrea el token de la probabilidad de distribución
                next_token = torch.multinomial(probs, 1)
            
            if return_iterations:
                # Mantenemos pista de todas las iteraciones para análisis
                iteration = {'input': ''.join(output)}
                best_n = sorted_tokens[:top_n].cpu().tolist()
                choices = {f'Choice #{choice+1}': f'{tokenizer.decode(token)} ({prob:.4f})' for choice, (token, prob) in enumerate(zip(best_n, probs[best_n].cpu().tolist()))}
                iteration.update(choices)
                iterations.append(iteration)

            output.append(tokenizer.decode(next_token))
            input_ids = torch.cat([input_ids, next_token.unsqueeze(dim=0)], dim=-1)

        output_text = ''.join(output)
        if not return_iterations:
            return output_text, None
        else:
            df = pd.DataFrame(iterations)
            return output_text, df

Ahora observemos que pasa cuando generamos texto con nuestra función y algunos parámetros.

Primero, observemos que pasa cuando pasamos un `eps=1` que quiere decir que la generación va a ser de tipo greedy:

In [7]:
output_text, iterations_df = generate(model, tokenizer, text, max_length=15, eps=1.0, top_n=10, return_iterations=True, device=device)
print(output_text)
iterations_df.head(15)

Había una vez un hombre que se llamaba a sí mismo "El hombre de la bolsa".

,input,Choice #1,Choice #2,Choice #3,Choice #4,Choice #5,Choice #6,Choice #7,Choice #8,Choice #9,Choice #10
0,Había una vez,un (0.3017),una (0.2506),", (0.1450)",en (0.0818),que (0.0596),... (0.0587),dos (0.0174),. (0.0072),tres (0.0067),uno (0.0034)
1,Había una vez un,hombre (0.1397),rey (0.0564),niño (0.0535),joven (0.0460),chico (0.0347),pequeño (0.0321),príncipe (0.0192),tipo (0.0166),muchacho (0.0164),viejo (0.0148)
2,Había una vez un hombre,que (0.3329),llamado (0.1111),", (0.0773)",y (0.0529),... (0.0431),de (0.0326),en (0.0320),con (0.0285),muy (0.0203),. (0.0126)
3,Había una vez un hombre que,se (0.1276),tenía (0.0634),vivía (0.0624),no (0.0623),era (0.0422),estaba (0.0276),amaba (0.0263),", (0.0255)",fue (0.0238),había (0.0182)
4,Había una vez un hombre que se,llamaba (0.1948),había (0.0505),enamoró (0.0370),sentó (0.0296),convirtió (0.0198),casó (0.0181),sentía (0.0149),hizo (0.0149),fue (0.0146),encontró (0.0121)
5,Había una vez un hombre que se llamaba,a (0.0438),... (0.0425),John (0.0128),""" (0.0104)",José (0.0101),David (0.0097),Peter (0.0088),Juan (0.0086),Henry (0.0081),A (0.0074)
6,Había una vez un hombre que se llamaba a,sí (0.8622),si (0.1250),él (0.0034),uno (0.0008),Sí (0.0007),un (0.0006),su (0.0005),mismo (0.0005),la (0.0004),engaño (0.0004)
7,Había una vez un hombre que se llamaba a sí,mismo (0.9944),propio (0.0017),misma (0.0015),m (0.0003),mismo (0.0002),a (0.0002),solo (0.0002),", (0.0002)",sí (0.0001),y (0.0001)
8,Había una vez un hombre que se llamaba a sí mismo,""" (0.1287)",el (0.0575),... (0.0179),un (0.0161),señor (0.0145),Señor (0.0144),Dios (0.0132),rey (0.0110),", (0.0099)",Capitán (0.0095)
9,Había una vez un hombre que se llamaba a sí mi...,El (0.0862),el (0.0581),Padre (0.0191),Dios (0.0169),Señor (0.0150),La (0.0131),señor (0.0124),Rey (0.0114),S (0.0096),Sr (0.0083)
10,Había una vez un hombre que se llamaba a sí mi...,hombre (0.0511),Hombre (0.0475),Rey (0.0344),Señor (0.0247),Gran (0.0144),rey (0.0107),Ca (0.0078),Santo (0.0074),Dios (0.0073),Diablo (0.0066)
11,Había una vez un hombre que se llamaba a sí mi...,de (0.3575),que (0.1314),del (0.0975),""". (0.0707)",""" (0.0266)",más (0.0235),""", (0.0157)",invisible (0.0140),sin (0.0114),con (0.0108)
12,Había una vez un hombre que se llamaba a sí mi...,la (0.3301),los (0.1126),las (0.1108),La (0.0239),hielo (0.0218),nieve (0.0163),mi (0.0156),mis (0.0138),hierro (0.0119),Dios (0.0099)
13,Había una vez un hombre que se llamaba a sí mi...,bolsa (0.0791),casa (0.0323),luna (0.0285),máscara (0.0281),hora (0.0267),basura (0.0173),calle (0.0162),capa (0.0136),Luna (0.0130),pistola (0.0127)
14,Había una vez un hombre que se llamaba a sí mi...,""". (0.5112)",""" (0.2015)",""", (0.1015)",de (0.0756),"."" (0.0320)","""... (0.0165)","""? (0.0045)",negra (0.0041),. (0.0023),del (0.0023)

Observamos como el input progresa a la vez que las opciones de tokens que hay. Sin importar cuantas veces invoquemos a la función con los mismos parámetros, siempre vamos a obtener los mismos resultados.

Ahora, observemos que pasa si introducimos exploración al reducir el `eps=0.5`, lo cual nos dice que aproximadamente la mitad de las veces va a elegir el siguiente token muestreando y la otra mitad explotando.

In [8]:
output_text, _ = generate(model, tokenizer, text, max_length=100, eps=0.5, device=device)
print(output_text)

Había una vez, en el Japón... un hombre que se llamaba a sí mismo "Hombre de ciencia".Pensaba que era un hombre de ciencia.Debe haber pensado que era un hombre de ciencia, porque era un hombre de ciencia.Pero no lo era.El hombre de ciencia era puro.Era puro y ya no lo era.El hombre de ciencia era puro.Era puro y ya no lo era.El hombre de ciencia era puro.Era puro y ya no lo era.¡No es verdad!¡Objeción

En este caso, cada vez que invoquemos a la función, vamos a obtener una respuesta diferente, a veces más coherente y otras veces menos. Vale la pena realizar varias pruebas para observar los resultados hasta encontrar un balance.

### Generando texto con las utilidades del modelo

Ahora, la clase de Huggingface implementa la función `generate` que hace la labor de generación por nosotros, incluyendo las opciones de muestreo y explotación como hemos observado. Solo que además permite otra serie de parámetros y opciones para controlar la generación de texto. Para más información se recomienda estudiar:

- [Natural Language Processing with Transformers: Building Language Applications With Hugging Face](https://www.amazon.com/Natural-Language-Processing-Transformers-Applications/dp/1098103246), Capitulo 5
- https://huggingface.co/docs/transformers/v4.41.3/en/main_classes/text_generation#transformers.GenerationConfig
- https://huggingface.co/docs/transformers/v4.41.3/en/main_classes/text_generation#transformers.GenerationMixin.generate

In [9]:
output = model.generate(tokens, pad_token_id=tokenizer.eos_token_id, max_length=100, do_sample=True, temperature=0.5, top_k=0)
print(tokenizer.decode(output[0]))

Había una vez una chica que era muy buena en la cama.Era como una madre para mí.Sólo que estaba demasiado ocupada intentando ser una buena madre.No quería que se casara con un hombre que no se podía permitir.Así que me fui a casa de mis padres.Y ella se fue a vivir con mi hermana.Así que me quedé con ella.Y ahora, estoy aquí.Y ahora, ella se ha ido.¿Qué quieres que haga, Ben?¿Qué quieres que haga?

## Fine tuning

Ahora, intentemos hacer fine tuning a nuestro modelo. Intentemos entrenarlo en un corpus de chistes en idioma español y ver como la narrativa de su output cambia.

##### Nota
Lastimosamente, este dataset es muy pequeño y la distribución del texto es muy diferente a la distribución de texto con la cual fue entrenado el modelo original, por lo que no se esperan resultados significativamente ejemplares. Sin embargo, el objetivo es observar como cambia la generación del texto una vez lo entrenamos en un conjunto especializado.

In [10]:
from datasets import load_dataset

dataset = load_dataset("mrm8488/CHISTES_spanish_jokes")
dataset

DatasetDict({
    train: Dataset({
        features: ['id', 'text', 'keywords', 'funny', 'category'],
        num_rows: 2419
    })
})

In [11]:
dataset['train'][0]

{'id': 0,
 'text': '- ¡Rápido, necesitamos sangre!\n- Yo soy 0 positivo.\n- Pues muy mal, necesitamos una mentalidad optimista.',
 'keywords': 'sangre',
 'funny': 1,
 'category': 'otros'}

In [12]:
dataset.set_format('pandas')
df = dataset['train'].to_pandas()
df.head(10)

,id,text,keywords,funny,category
0,0,"- ¡Rápido, necesitamos sangre!\n- Yo soy 0 pos...",sangre,1,otros
1,1,- ¿Cuál es el mejor portero del mundial? \n- E...,"futbol,porteros",1,otros
2,2,El otro día unas chicas llamarón a mi puerta y...,"dinero,agua",1,otros
3,3,"- Andresito, ¿qué planeta va después de Marte?...",planetas,1,profesiones
4,4,- ¿Por qué Bob Esponja no va al gimnasio? \n- ...,"esponja,gimnasios",1,otros
5,5,Van dos ciegos y le dice uno al otro: \n- Ojal...,ciegos,1,otros
6,6,Noticia de última hora!! \n\nMuere una suegra ...,"canarias,coches,noticias",2,familia
7,7,"– Mamá, mamá, en el colegio dicen que estoy lo...","locos,sillas",1,familia
8,8,"– Mamá, mamá, ¿me haces un bocata de jamón?\n–...","madres,jamón",1,otros
9,9,- Qué pasa si te expulsan de cuatro univerdade...,"universitarios,universidades",1,otros

In [13]:
df['Palabras por chiste'] = df['text'].str.split().apply(len)
df['Palabras por chiste'].median()

np.float64(31.0)

Aquí podemos observar que la mediana de longitud en terminos de palabras es de 31. Esto es esperado, pues los chistes deben ser cortos por naturaleza. Por otra parte, es bastante claro que el corpus original del modelo pre-entrenado contenía texto muy diferente a este, por lo que la calidad de los resultados, sin hacer mayores modificaciones puede que no sea buena.

Sin embargo, a manera demostrativa, continuarémos con el ejercicio, prepararémos el conjunto de datos para entrenamiento.

In [14]:
def preprocess_function(max_len):
    def _preprocess_function(examples):
        return tokenizer(examples['text'], max_length=max_len, truncation=True, padding='max_length')
    return _preprocess_function

Los modelos GPT no esperan otra cosa más que los `input_ids`, por lo que retirarémos todas las demás columnas del dataset ya que no nos son de utilidad en este momento.

In [15]:
dataset.reset_format()
tokenized_dataset = dataset['train'].map(preprocess_function(max_len=512), batched=True)
tokenized_dataset = tokenized_dataset.remove_columns([col for col in tokenized_dataset.column_names if col != 'input_ids'])
tokenized_dataset = tokenized_dataset.train_test_split(train_size=0.9)
tokenized_dataset.set_format('torch')
tokenized_dataset

DatasetDict({
    train: Dataset({
        features: ['input_ids'],
        num_rows: 2177
    })
    test: Dataset({
        features: ['input_ids'],
        num_rows: 242
    })
})

Finalmente procedemos a definir el entrenamiento. Observaremos que es muy similar a como entrenamos a BERT.

In [18]:
from transformers import DataCollatorForLanguageModeling
from transformers import Trainer, TrainingArguments


batch_size = 8 if IN_COLAB else 2
logging_steps = len(tokenized_dataset['train']) // batch_size
# Definimos los parámetros globales de entrenamiento
training_args = TrainingArguments(
    output_dir='./hf-gpt',
    num_train_epochs=10,
    learning_rate=2e-5,
    per_device_eval_batch_size=batch_size,
    per_device_train_batch_size=batch_size,
    weight_decay=0.01,
    eval_strategy='epoch',
    save_strategy='epoch',
    load_best_model_at_end=True,
    disable_tqdm=False,
    logging_steps=logging_steps,
    report_to='none'
)

# Y definimos el entrenador, especificando el modelo, datasets y el tokenizador
trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False),
    train_dataset=tokenized_dataset['train'],
    eval_dataset=tokenized_dataset['test'],
)

In [19]:
%%time
trainer.train()

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

CPU times: total: 14min 49s
Wall time: 15min 7s

TrainOutput(global_step=10890, training_loss=2.3891638770685817, metrics={'train_runtime': 906.7026, 'train_samples_per_second': 24.01, 'train_steps_per_second': 12.011, 'total_flos': 5688327536640000.0, 'train_loss': 2.3891638770685817, 'epoch': 10.0})

Ahora observemos los resultados.

In [20]:
output = model.generate(tokens, pad_token_id=tokenizer.eos_token_id, max_length=100, do_sample=True, temperature=0.8)
print(tokenizer.decode(output[0]))

Había una vez un ciego con sus gafas.
- Oye, ¿como se dice ciego?
- Yo no tengo.
- Yo se como se dice ciego.
- Pues no se, pero que quieres que te diga ¿en qué se parece uno con los ojos?
- Que en que le falta el ojo izquierdo...
- Y que no tiene derecho a nada.
- Eso no es verdad... ¿A qué te refieres?
- Que se le ha quitado el derecho a

In [21]:
output_text, _ = generate(model, tokenizer, text, max_length=100, eps=0.2, device=device)
print(output_text)

Había una vez una presentadora de televisión que se llamaba María Julia , y cubría 4 millones de televidentes. Cuando estrena un nuevo programa de televisión trata este tema de la televisión telefónica , que consiste en que la persona que llama no llegue a suidencia por teléfonocon segundo.
En el mismo programa trata este tema de fortuna y matrimonio.
Cuando Eva se va de casa se encuentra a la presentadora de televisión como a un novio en medio de la noche. Al finalizar la noche invita a la presentadora

No parece ser muy gracioso precisamente, sin embargo, notemos que la generación de texto cambia de "estilo", ahora es mucho más frecuente encontrar conversaciones cortas, frases concisas, y situaciones particulares, en lugar del estilo más literario del modelo original. Esto es un indicio de la influencia que tiene el conjunto de datos de entrenamiento en el modelo final, esto es algo a tener muy en cuenta a la hora de utilizar y hacer fine tuning a modelos de lenguaje.

## Conclusiones
- Los modelos BERT y GPT son muy similares, aunque ambos tienen diferencias claras en cuanto a su estructura y manera de entrenamiento.
- Sin embargo, ambos pueden utilizarse para el mismo tipo de tareas posteriores, lo cual sustenta la importancia del pre-entrenamiento y la construcción de embeddings de buena calidad.
- En los modelos generativos, tiende a ver un dilema de tipo exploración-explitación, al explotar los resultados, podemos ser más precisos, per al mismo tiempo más monótonos, mientras que explorando podemos ser más creativos y diversos, pero al mismo tiempo terminar con texto incoherente, difuso o alucinante. Es necesario evaluar la tarea a la mano para escoger el ajuste adecuado entre estas dos técnicas de decodificación.
- Los modelos generativos de texto no son más que una gran probabilidad de distribución y esta a su vez es completamente dependiente de los datos con los que fue entrenada. Es aquí donde se hace sumamente importante obtener y curar los conjuntos de datos con los que se entrena, de lo contrario se puede terminar con un modelo de mala calidad para la tarea en especifico.
- Diferentes estrategias de decodificación entregan resultados diferentes, vale la pena hacer una exploración de los resultados y ajustar los hiperparámetros para obtener los resultados deseados según el objetivo.